In [3]:
class Emp:
    count=0 
    emps=[] 
    def __init__(self,name,family,salary,dept):
        self.name=name
        self.family=family
        self.salary=salary
        self.dept=dept
        Emp.count=Emp.count+1 
        Emp.emps.append(self) 
        

    def average_salary(self):
        return sum(emp.salary for emp in Emp.emps) / Emp.count
    
class Fulltime_Emp(Emp):
        pass
emp1 = Emp("Jyoshna Yarraguntla", "Yarraguntla Family", 9999, "CS")
emp2 = Emp("Jane Smith", "Smith Family", 8888, "CS")
full_time_emp = Fulltime_Emp("John Doe", "Doe Family", 9998, "Management")
print(emp1.average_salary())
print(emp2.average_salary())
print(full_time_emp.average_salary())  


9628.333333333334
9628.333333333334
9628.333333333334


In [4]:
import numpy as np 

sampl=np.random.uniform(low=1,high=20,size=20) 
reshape_arr=sampl.reshape((4,5)) 
print(reshape_arr)
np.where(reshape_arr== np.max(reshape_arr, axis=1, keepdims=True), 0, reshape_arr)






[[ 8.20923257 17.31275075  6.33132799  5.0689668   2.91210173]
 [ 9.41998103  9.23728782 17.55746007  3.06825426  1.96417563]
 [ 3.30807907  2.84059672 19.63581772 15.3359931  14.63724424]
 [18.42559251  1.64686591 15.95293208 14.47347435 19.3666904 ]]


array([[ 8.20923257,  0.        ,  6.33132799,  5.0689668 ,  2.91210173],
       [ 9.41998103,  9.23728782,  0.        ,  3.06825426,  1.96417563],
       [ 3.30807907,  2.84059672,  0.        , 15.3359931 , 14.63724424],
       [18.42559251,  1.64686591, 15.95293208, 14.47347435,  0.        ]])